# Generated by Django 2.2.28 on 2022-06-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'course')},
        ),
    ]
